### PR TITLE
Move vuetify to dependencies

### PR DESCRIPTION
**Pull request by htanjo**
It worked, but "vuetify" should go into "dependencies" rather than "devDependencies".

### CODE REVIEW

**Comment by mornir** [comment]
@johnleider Hi John. In the quick start from the docs, it is advocated to install Vuetify under the devDependencies. Intuitively, I would install it as a dependency. Why is it better to add Vuetify as a devDependency?

**Comment by mornir** [comment]
Actually I've just noticed that Vuetify has already been moved to the "dependencies". The quick start should be updated accordingly if this is the correct way to install Vuetify.

**Comment by johnleider** [comment]
It honestly does not matter where you install it.

**Comment by mornir** [comment]
Ah ok. Thanks. I guess you can reject this pull request since Vuetify is already listed under the "dependencies".

**Comment by htanjo** [comment]
Yep, this PR is no longer necessary. Closing.
Thanks @mornir @johnleider

**Pull request closed without merging**
