### PR TITLE
Use ~ to import vuetify from node_modules

### PR DESCRIPTION
**Pull request by nkovacs**
I have not tested this with the template, only in my project, but it should work.

See https://github.com/shama/stylus-loader#usage

### CODE REVIEW

**Comment by mornir** [comment]
@nkovacs Hi. I'm curious. What are the benefits of writing @import '~vuetify/src/stylus/main' over @import '../node_modules/vuetify/src/stylus/main'?

**Comment by nkovacs** [comment]
It doesn't depend on the location of the component in relation to node_modules. It's the proper way to import from node_modules.

**Comment by mornir** [comment]
I see. Thanks for the answer.
It might look a bit confusing for people not familiar with the use of the "tilde" syntax.

**Comment by johnleider** [comment]
All pull requests should be made to dev, thank you!

**Pull request closed without merging**
